# Generated by Django 4.2.4 on 2023-09-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectroMasterAdminSide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Descriptio_n', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Product_Image', models.ImageField(blank=True, null=True, upload_to='Images2')),
            ],
        ),
    ]
