# Generated by Django 4.2.4 on 2023-10-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectroMasterUserSide', '0002_logindb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USer_NAme', models.CharField(blank=True, max_length=100, null=True)),
                ('PRoduct_NAme', models.CharField(blank=True, max_length=100, null=True)),
                ('DEscription', models.CharField(blank=True, max_length=100, null=True)),
                ('QUantity', models.IntegerField(blank=True, null=True)),
                ('TOtal_PRice', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
